### ISSUE TITLE
bx-viewport calculated height

### ISSUE THREAD

**Issue by romelmederos** [stevenwanderski/bxslider-4#103]
BxSlider v4.1 - Fully loaded, responsive content slider
Having issues with the rendering of the slider since I am using percentages for the height in a responsive web site for mobile.

So I had to  make the change
 from:
slider.viewport.css('height', getViewportHeight());
to this:
slider.viewport.css('height', '');

I altered the plugin with an option instead in my copy, but the quickest way to change is by modifying the line above.

**Comment by wannaco** [comment]
Not sure If anyone found a way to resolve the above but here is what I came with. the slider.viewport.css uses the parent elemnt, so if you need to use `<display:none>` you can target the child elements and add `<display:block>` via jquery later, it work for me at least.

**Comment by GRAFIX21** [comment]
Just an idea because I had the same issue today. In my case the container around the slider was the problem because it had no width set or was squeezed togetther horizontally by the surrounding grid. And in my case too the slider collapsed vertically after loading. My solution was, to add style="width:100%;" to the container around the slider.
