### ISSUE TITLE
slider with scrollbar as design

### ISSUE THREAD

**Issue by dohomi** [stevenwanderski/bxslider-4#194]
Hello,

is it possible to use a x / y scrollbar mechanism with this bxslider? I've seen examples for clicking through the slides, I would like to show a scrollbar whith a handle to scroll left / right. Is this possible?

Thanks,
Dominic

**Comment by Tidal-Wave** [comment]
This request seems better suited to building out your own  div and css with `overflow-x` set to scroll. If you are looking to generate a pseudo scroll bar to control the slide show there is currently nothing built into bxslider to do this. If you would like to make a feature request for this please open a new issue and we will consider it for a future update.

Closing because this is currently out of scope and housekeeping.
