### ISSUE TITLE
Swipe gesture on iPhone, iPad, etc. crashes site

### ISSUE THREAD

**Issue by justiny** [stevenwanderski/bxslider-4#222]
It seems that the bxslider swipe gesture on any mobile device crashes the site.  It seems consistent on every attempt, no matter what the slider settings are.  Has anyone noticed this issue?  

Thanks

**Comment by Tidal-Wave** [comment]
Hello all, i've been added to this project to help maintain it and provide updates. Sorry for any lack of communication, we hope to begin pushing updates soon.

This seems to be related to https://github.com/stevenwanderski/bxslider-4/pull/596, and we are aware. Therefore I am going to close this issue because of duplication and housekeeping, but we are reviewing fixes for our next update.
