### ISSUE TITLE
JQuery 1.7.1

### ISSUE THREAD

**Issue by lionelB** [stevenwanderski/bxslider-4#229]
hello,

I would like to know if bxslider4 could work with jQuery 1.7.1 ?
Is there particulars features from jQuery 1.8.2 that are not in 1.7.1 ?
thanks

**Comment by Tidal-Wave** [comment]
Hello, i've been added to this project as a maintainer. I have not tested bxSlider with 1.7 but 1.8 introduced [a lot of fixes] (http://blog.jquery.com/2012/08/09/jquery-1-8-released/) to transitions, animations, older browser support, etc. 

We are currently reviewing issues for an update. At a later date we can review and test jQuery versions, but since this isn't a pressing issue I am closing this for now.

**Comment by lionelB** [comment]
no problem
