### ISSUE TITLE
slider.reloadSlider is not a function

### ISSUE THREAD

**Issue by dannysouza16** [stevenwanderski/bxslider-4#289]
My code is like this:

var slider = $('.slider').bxSlider({ ... });

$('.reload').click(function(){	
  slider.reloadSlider({ ... });
});

and On click, I want to reload the slider or Destroy and reload .. but when I click to reload the slider , on my console show like this > slider.reloadSlider is not a function.

Sorry for my grammatics mistakes..

**Comment by Tidal-Wave** [comment]
Closing because your two jsfiddles are full of errors. As pointed out, your reloads don't have ids so they don't even work, and when you don't load any config on bxslider it uses all defaults. Everything you posted is behaving as expected considering the above issues. 

@stereoscott I have been added to help maintain this project and provide updates. I will evaluate your assumption at a later date.

**Comment by keya129** [comment]
Yes, I also faced that issue many times theoritical if i speak, you should use the reload slider after bxSlider JS, and the variable holding the object of bxSlider should be kept global, before ready function

**Comment by amamwho** [comment]
http://jsfiddle.net/G8Laq/27/

that works. thank you. @stereoscott
