### ISSUE TITLE
Automatically create thumbnails

### ISSUE THREAD

**Issue by cliffordp** [stevenwanderski/bxslider-4#309]
Re: http://bxslider.com/examples/thumbnail-pager-1

It'd be ideal if the thumbnails didn't need to be manually added and just displayed the large image/content in smaller dimensions.

Thank you.

**Comment by cliffordp** [comment]
ok then... :-1:

**Comment by Tidal-Wave** [comment]
Im sorry, I don't mean to be short, but because I have been added to maintain and provide updates to this project I have a lot of work to do to bring this project up to date. We have plans to revisit how thumbnails are generated using data attributes in a future update, but first I need to address more immediate bug issues for the community as a whole. We are not dismissing this request, just deferring it to a later date.

**Comment by cliffordp** [comment]
Thanks for the commentary :+1:
