### ISSUE TITLE
Issue in Chrome with infinite carousel

### ISSUE THREAD

**Issue by kylepeters** [stevenwanderski/bxslider-4#347]
I like this carousel, but I am concerned about a particular behavior in Chrome - I am registering a jQuery hover() event that doesn't work after the slides are restarting.  Below is my code that can re-create the issue in Chrome, and an image illustration of the issue...

...
$(document).ready(function(){
    //instaniate bxslider
    $(".slider").bxSlider({
        mode: "horizontal",
        useCSS: false,
        speed: 500,
        slideMargin: 5,
        easing: "easeInOutCubic",
        slideWidth: 50,
        minSlides: 4,
        maxSlides: 16,
        moveSlides: 4,
        pager: false,
        controls: true,
        responsive: false
    });
    //register hover event (lift the slide 10 pixels) to all slides
    $(".slider > div").hover(
        function () {
            $(this).animate({ top: "-10" }, 300, "easeInCirc", function () { });
                }, function () {
            $(this).animate({ top: "0" }, 300, "easeOutCirc", function () { });
    });
});
...

    <pre>
    <div class="slider">
      <div class="slide"><img src="http://placehold.it/50x150&text=1"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=2"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=3"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=4"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=5"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=6"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=7"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=8"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=9"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=10"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=11"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=12"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=13"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=14"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=15"></div>
      <div class="slide"><img src="http://placehold.it/50x150&text=16"></div>
    </div>
    </pre>

![poc_bxslider](https://f.cloud.github.com/assets/5631186/1283185/bafe0606-2f80-11e3-9d56-92c6e1615b68.jpg)

**Comment by Tidal-Wave** [comment]
I think what is happening here is that infinite scroll uses a cloning method to achieve the effect. This is probably causing an issue with you event binding.

**Comment by Tidal-Wave** [comment]
possible fix here: https://github.com/stevenwanderski/bxslider-4/issues/346. Looking to put this in next update.

**Comment by kylepeters** [comment]
Tidal-Wave (Steven),

Thank you for your reply.  I am confused on the solution though. I followed the link you sent, but I am unclear on how to implement the fix.  Do I simply get the latest release of bxSlider to remedy the issue?

**Comment by Tidal-Wave** [comment]
Sorry, to clarify: I've recently been added as a main contributor to this project, and am working on releasing a much needed update to this project and then will maintain it in the future. The problem you had revolves around how the current code clones slides for infinite scrolling. I'm not happy with how this works in general, but need time to address all the issues.

The fix I linked hasn't been implemented yet. I am combing through issues at the moment and trying to organize things.  I plan on eventually reevaluating infinite scroll, but for now if you make the adjustment linked it may solve your issues. 

I will push this fix in a week or so and update bxslider with a ton of issues and this will be a temporary solution until we redo infinite scroll. 

I'm pretty sure this is the fix for your issue. If you need an immediate fix it should be easy to implement in your local version. If you want to wait for me to update please bear with me.

**Comment by Tidal-Wave** [comment]
Confirmed fixed in 4.1.3 update. Pushing soon.

**Comment by Tidal-Wave** [comment]
@kylepeters I just pushed 4.1.3 and tested your use case. Issue seems resolved.
