### ISSUE TITLE
bxSlider breaks position:fixed header on scroll

### ISSUE THREAD

**Issue by BPUserX** [stevenwanderski/bxslider-4#422]
Any page that I am calling the bxSlider and also have a position:fixed header element the header goes all buggy on scroll. The header no longer stays fixed to the top of the screen and starts leaving tracers during scroll.

I have turned on and off every possible element on my page for debugging and it is 100% the bxSlider causing this erratic behavior.

http://verrado.bigfishstage.com/life-verrado/schools-verrado/more/

**Comment by BayarkhuuBataa** [comment]
I have the same problem. Have you found a solution yet?

**Comment by jpjmortimer** [comment]
useCSS: false,

This worked for me.  I had a parent element with fixed positioning and without above I would get white slides of death.

**Comment by Tidal-Wave** [comment]
Please make sure you are not using the download from the website. I have no control over it and it is several versions old. 

If you are still experiencing issues after pulling the latest version from here, please open a new ticket. I am in the process of a complete rewrite, but it has been slow since I am the only active member of this project currently.
