### ISSUE TITLE
Responsiveness Not Work

### ISSUE THREAD

**Issue by linzthephotog** [stevenwanderski/bxslider-4#487]
When a phone is rotated the gallery is not fitting to the screen. 
![screen shot 2014-03-04 at 16 49 43](https://f.cloud.github.com/assets/7003479/2465926/82eef3d0-afa8-11e3-908a-1a2904a42cc8.png)
![screen shot 2014-03-04 at 16 49 53](https://f.cloud.github.com/assets/7003479/2465927/82ffb7f6-afa8-11e3-8887-215d43ce678f.png)

**Comment by Tidal-Wave** [comment]
Due to lack of example in OP issue I am going to close this. We are aware of some issues with responsiveness but can't reproduce this specifically with the information provided, and the other demo provided by @gnowland  is currently down. We would be happy to reevaluate this if someone wants to put together an example and provide more info, currently we are focusing efforts on a much needed update and housekeeping.

**Comment by gnowland** [comment]
@Tidal-Wave, this issue is a duplicate of an issue I opened and which contains a fix generously provided  by @kellykarnetsky: https://github.com/stevenwanderski/bxslider-4/issues/611#issuecomment-68372450 . His code should possibly be considered for a merge to stop this behavior from happening for others! Cheers, and thanks for continuing development on this killer slider plugin!

**Comment by Tidal-Wave** [comment]
Good to know @gnowland. I am attempting to clean house and get things back up to par, so sorry if I am blowing through issues but I have a lot of ground to cover. I will review the mentioned issue and include any fixes in our next update. 

Cheers.
