### ISSUE TITLE
Bxslider and Bootstrap 3 tabs

### ISSUE THREAD

**Issue by javieraraneda** [stevenwanderski/bxslider-4#550]
Hi Steven,

On Bootstrap 3 i tried to put different sliders for each tab. When website loads first time everything okay but when I change div bxslider is not loading and showing content truthfully. Take a look the attachments:

Tab 1
![tab-1](https://cloud.githubusercontent.com/assets/3931328/3058958/e92918aa-e1e5-11e3-84c8-5ac3b99c4f8d.png)

Tab 2
![tab-2](https://cloud.githubusercontent.com/assets/3931328/3058964/f53651ee-e1e5-11e3-9d6c-484c474aaa4c.png)

Thanks in advance for any help on this.

**Comment by Tidal-Wave** [comment]
Hi, I have been added to help maintain this project. As we try to prep for an update I am closing any issues that don't have working examples available in order to get some house keeping done. @pedjamarkovic if you have a similar issue please feel free to start a thread of your own with as much detail as possible, including an example of the issue.
