### ISSUE TITLE
bx_loader.gif not loading

### ISSUE THREAD

**Issue by shainanand** [stevenwanderski/bxslider-4#592]
The loader image(bx_loader.gif) is not loading before the slide images are fully loading . Please help me in resolving the issue.

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and example of issue. If you would like support please provide at minimum a bare bones example of the issue.

**Comment by samstoller** [comment]
I'm also experiencing this issue, can we reopen?
It's a problem with the order in which the browser is downloading the loader and slider images. The loader GIF is not processed until after all slides have been loaded, which results in the following:
1. DIV is inserted into the DOM with a class of 'bx-loading'
2. Loading GIF is not preloaded, so a blank DIV is rendered
3. Slider images are loaded by the browser
4. Loading GIF is loaded by the browser
5. Slider is started 
6. Loading GIF is hidden
7. Slider is made visible

So in other words, the GIF is loaded and displayed, it just happens after all the slider images have been loaded which means users won't see the loading GIF because the slider is started immediately after it renders. 

The fix to this would be to preload the loader image before inserting it into the DOM.

A workaround is to do the preloading yourself, however this is a bit hacky as you typically have to insert extraneous HTML, CSS and/or JS depending on the preloading method you implement. It would much better to see the plugin handle this instead.

Here is a SO question on the same issue: http://stackoverflow.com/questions/21513161/bxslider-wont-load-loading-animation-bx-loader-gif-before-the-slide-images

Thanks.

**Comment by Tidal-Wave** [comment]
This should be addressed in the next update, which might just be today. Hold tight.

**Comment by samstoller** [comment]
Fantastic.
