### ISSUE TITLE
A method to destroy the bxSlider so it can be restarted OR a reset method

### ISSUE THREAD

**Issue by shakeebahmed** [stevenwanderski/bxslider-4#60]
I have a scenario wherein I have to destroy the slider and have it back up again on some event. A destroy method would really be useful

**Comment by edwardgoodnow** [comment]
with multiple sliders this option fails to work....instead try this
selector = your ajax element

if($(selector).parent().parent().hasClass('bx-wrapper')){
                  classes = $(selector).attr('class');
                  id=$(selector).attr('id');
                  alt=$(selector).attr('alt');
                  title=$(selector).attr('title');
                  reload =1;
                    $(selector).parent().parent().replaceWith('<ul id="' + id + '" class="' + classes + '"></ul>'); 
                } 


I have actually modified this library myself to use Ajax within the slider itself, so that it can more easily deal with pagination created by AJAX.....I do however use this method when I want to destroy the entire element and reload it with AJAX form results and such
