### ISSUE TITLE
destroySlider() method in the minified version of the slider does not remove the style attribute as it is supposed to in unminified version

### ISSUE THREAD

**Issue by frensuren** [stevenwanderski/bxslider-4#644]
Manually minified the the source code and seems to work. Looks like there is a problem in the minified version.

**Comment by Tidal-Wave** [comment]
Hey guys, I've been added to the project to maintain it and provide updates. I'm aware that there are some parity issues with the minified and unminified versions. We. Intended to fix this in our next update and also create a build workflow to avoid this in the future. 

Closing this for now due to duplication and housekeeping. Will address very soon.
