### ISSUE TITLE
Browser Search (ctrl/cmd + f) breaks alignment

### ISSUE THREAD

**Issue by SoapSuds92** [stevenwanderski/bxslider-4#661]
I have a slider that has slides with both images and text on them. When the user uses the browsers search feature (usually ctrl or cmd + f) and types in text that is on a slide, the slider will jump to that slide and break out of alignment. See the attached screenshots.

![screen shot 2014-10-28 at 4 41 01 pm](https://cloud.githubusercontent.com/assets/3931162/4816793/da21173e-5ee2-11e4-92df-b50289263dae.png)
![screen shot 2014-10-28 at 4 41 30 pm](https://cloud.githubusercontent.com/assets/3931162/4816792/da19fcec-5ee2-11e4-92a5-41c4c4125d3a.png)

**Comment by Tidal-Wave** [comment]
Im not sure there is a way to even fix this issue. While it would be possible to prevent keystrokes with javascript, AFAIK you can't prevent someone from using the browser menu, and one shouldn't be able too. 

If you look at some of the other [more advanced sliders] (http://bqworks.com/products/advanced-slider/responsive.html) they also suffer from this issue. 

Im closing this issue because I don't think there is a good way to solve it currently.
