### ISSUE TITLE
vertical slidershow issue

### ISSUE THREAD

**Issue by jivanshr** [stevenwanderski/bxslider-4#663]
Hi Steven 

I am designer lead from sageframe CMS.
In our home page, http://sageframe.com
I am using bx slider as vertical slideshow. i got critical problem in firefox browser in android OS.
I see it is not working your demo page too
http://bxslider.com/examples/vertical-slideshow

I would be much grateful if you provide the solution.

Regards
Jivan

**Comment by Tidal-Wave** [comment]
Closing due to lack of information and example. Possibly related to https://github.com/stevenwanderski/bxslider-4/pull/596.

We are looking at mobile issues with our next update. The page you linked currently doesn't seem to have a vertical slider on it. If our upcoming update doesn't address any issues you had, please feel free to reopen with an example and more information.
