### ISSUE TITLE
Please rename this project to bxCarousel

### ISSUE THREAD

**Issue by DelvarWorld** [stevenwanderski/bxslider-4#673]
This is a carousel plugin, not a slider. Makes it hard to find carousel plugins and hard to find slider plugins :)

**Comment by Tidal-Wave** [comment]
At this point in time we politely disagree and decline. BxSlider is, imo, actually a slider, but depending on your definitions it could be considered both actually since it has the ability to page multiple slides on a slide or a single image.

TL;DR - At this point we are inclined to say [tomato / tomahto]. (http://ux.stackexchange.com/questions/13951/what-is-the-difference-between-a-slider-a-gallery-and-a-carousel).
