### ISSUE TITLE
Issues with images not displaying at correct size initially

### ISSUE THREAD

**Issue by craigcpaterson** [stevenwanderski/bxslider-4#681]
Hi,
I have implemented an instance of bxSlider on my site and it is almost perfect, but the images do not show at the correct size until the browser is resized. Works OK in IE11 on Windows 8.1, but not working in Chrome, or in Safari, Chrome on Mac.
Link to dev site – http://d.pr/1ak0f
Thanks

**Comment by Tidal-Wave** [comment]
Hey there @craigcpaterson, I've been added to the team to help maintain the project. I apologize on behalf of the team for any lack of communication, and I will be helping get things back in order for this project. 

I looked at the page you linked but it seems you may have moved to another slider. I didn't see any bxSldier code on your site. 

Im going to close this issue for now because we are trying to clean up issues and get ready for future updates. If you want to pursue the issue further and have something I can look at, please feel free to reopen your issue.

@8Sarit, @AronPride  -  If you haven't yet created your own issue please do so and I will get to it ASAP. Please provide as much information and sample code as possible.
