### ISSUE TITLE
Moving captions outside

### ISSUE THREAD

**Issue by curvedb** [stevenwanderski/bxslider-4#700]
Is there a way to move the captions outside of the wrapper?

**Comment by Tidal-Wave** [comment]
Hey there guys. My name is Eric and I have been added to this project to help maintain it and provide updates. Sorry for any lack of communication, we will be addressing that and moving updates in the coming year. 

As far as moving the captions: Currently the plugin generates its captions by pulling from the image `title` attribute and adds a div `bx-caption` to the slide, so you are correct that it will be inside the wrapper.

I am working to provide some urgent immediate updates for a upcoming 4.2 patch, but we do plan on addressing captions in an upcoming update, probably 4.3 unless I start to pick up PR steam from the community. 

Im going to close this issue for now because we are trying to clean house, but know that we will be circling back around to look at this.
