### ISSUE TITLE
flexible slide width on ticker?

### ISSUE THREAD

**Issue by pleasantBailey** [stevenwanderski/bxslider-4#707]
I have a series of organization logos set to display in a ticker ("Previous clients include:"), and not all of these logos are the same relative dimension. Some companies just have really long or really short branding. 

Is there a way to get this working with a different/flexible width for each slide? I either end up with the wider logos being scaled, or the shorter ones having a ridiculous amount of space between them and the adjacent ones.

**Comment by Tidal-Wave** [comment]
Hey @pleasantBailey, my name is Eric and i've been added to the project to help maintain it. I apologize for any lack of communication. 

If I'm understanding your issue, currently, no, theres no way to adjust the width of the slider per slide as it transitions, because the images are floated into containers (why the smaller ones gap) and use responsive css to scale images into them (why the larger ones scale). 

One work around is to decide on a nice median width and create slides to use. for example you could put two small logos on one slide and use one large logo on another slide to achieve the effect you want. The key is to make sure that your slides are the same w/h. 

Im going to close this issue for now because we are trying to clean up issues and prepare for updates. Please feel free to reopen the issue with more information if I have misunderstood.
