### ISSUE TITLE
Ticker remember position possible / history

### ISSUE THREAD

**Issue by fourroses666** [stevenwanderski/bxslider-4#708]
First of all this is really an awesome script. Thanks allot for providing it. Using it for many sites.

Its not really really important but is there a way it remembers its position?
I have the ticker working on my site but when loading a new page the ticker starts with the first one.
Would be nice if it continued.

Second question: can the ticker scroll to the other side? (from left to right)

**Comment by Tidal-Wave** [comment]
Hey @fourroses666 - Thanks! My name is Eric and i've been added to the project to help address issues and update the script. 

As far as remembering its position, that would require some method of passing along the current slide on page load, and as of yet there is nothing in bxSlider to do that. You could probably use the callbacks and update a cookie as an example of the top of my head. 

Second question: Yes, `autoDirection` is honored by the ticker mode. Use `next` or `prev`  to set direction.

Im going to close this issue for now because we are trying to clean house and prepare for future updates.
