### ISSUE TITLE
Issue with colorbox + smoothzoom

### ISSUE THREAD

**Issue by kapadiapankit** [stevenwanderski/bxslider-4#709]
Hi,
I have used colorbox on slider images. And to zoom and pan I am using Smooth Zoom plugin on colorbox.
Zoom plugin link: http://vectorflower.com/preview/smooth_zoom/

I have tried zoom plugin with different slider and it worked. But I am used to with bxslider and I want to use it with bxslider.

Kindly check and help me out.

Thanks & Regards,
Pankit Kapadia

**Comment by Tidal-Wave** [comment]
Hello @kapadiapankit, my name is Eric and I have been added to the project to assist in maintaining it. I apologize for any lack of communication, we are working to address issues and update the plugin.

Do you have an example of the issue you are having? As we work to fix issues and prepare to update bxSlider, we want to be helpful, but need specific examples of issues with code in order to provide assistance in a timely manner as we bring the project up to date.

**Comment by kapadiapankit** [comment]
Hi,
Thanks for the reply. I have created test page. Here is a link: http://kapadiapankit.in/github-issue/
You can download all the files here: http://kapadiapankit.in/github-issue/github-issue.zip

I have used Colorbox+Smoothzoom plugins with different slider in a same way. Problem is only when I use bxSlider. 

Thanks,
Pankit Kapadia

**Comment by Tidal-Wave** [comment]
Thanks for creating this. We will look at it asap.

**Comment by Tidal-Wave** [comment]
This issue is because of the way `infiniteLoop` currently works. We are cloning the slides onto either side for the effect, and this duplicates your ids. You can fix this by using `infiniteLoop: false`.

**Comment by kapadiapankit** [comment]
@Tidal-Wave Thanks a lot ! I forgot to check rendered HTML. :+1:
