### ISSUE TITLE
Carousel: slide Nr. 2 is rendered for a small moment between other slides (visual bug)

### ISSUE THREAD

**Issue by 01Kuzma** [stevenwanderski/bxslider-4#727]
Hi!
I have a issue with a visual bug, here, in second part I've described it:
http://stackoverflow.com/questions/28244022/centering-bxslider-carousels-slides-with-fixed-grid-and-breakpoint

The bug: http://i.imgur.com/HDbUSrb.jpg
The code: http://jsfiddle.net/feyv2afw/

How it could be fixed ASAP?

Thank you!

**Comment by Tidal-Wave** [comment]
This happens because of wrap. You enforce a max width  that is less then the total sum of its parts and you have infiniteLoop, which forces this visual bug. You can see it stop by removing the max-width injection. You need to seriously rethink your approach on this. You also do a constant reload on window resize which causes flickering issues with your images. 

As much as I like for people to use bxslider, if you really really need this effect I might suggest you take a look at Owl Carousel 2. It has this feature built in. After I get bxslider up to date over the next few updates I will be revamping it to include features like this, but unless you more experienced with JS and CSS you are going to have a difficult time atm.

**Comment by 01Kuzma** [comment]
understood! Thank you very much for explanation!
