### ISSUE TITLE
Trying to move captions outside

### ISSUE THREAD

**Issue by curvedb** [stevenwanderski/bxslider-4#728]
I am trying to move bxslider captions outside of slider. Since there is "overflow: hidden" I can't do it with just css. I have tried to change this line 
```
$("this").append('<div class="bx-caption"><span>' + title + '</span></div>');'
```
to
```
'$(.captions).append(title);
```
Somehow it doesn't updated with each slide's title dynamically.
Any suggestions?

**Comment by curvedb** [comment]
I found this code but couldn't find where should I add 
```
$('.captions').html(slider.children.eq(slider.active.index).find('img:first').attr('title'));
```

**Comment by Tidal-Wave** [comment]
You should be able to alter the slider CDs to make the captions not absolutely float over the slide, if I understand what your trying to do. if you are trying to place captions completely outside of bxslider viewport that will require some JS. 

As far as the code you posted, it doesn't work because the way it is scoped.

**Comment by Tidal-Wave** [comment]
I'm sorry, "alter the slider CSS". Commenting from a phone.
