### ISSUE TITLE
When use captions img title= then hover img shows popup

### ISSUE THREAD

**Issue by fourroses666** [stevenwanderski/bxslider-4#730]
Just a minor thing:
When you use img title= then when hover a image it shows the default popup.
Maybe we better can use alt= for captions? 
(maybe its already possible)

![example](https://cloud.githubusercontent.com/assets/523389/6019587/811d4768-aba2-11e4-8054-22abf07a655e.png)

**Comment by Tidal-Wave** [comment]
Yea, I don't agree with the current method of captions either because of this and other reasons. I plan on redoing this with data attributes soon. 

For now if you need captions you can manually create them in each slide and turn off auto captions for bxslider. If you use the same class you can easily mimic the current captions. This will prevent this.

**Comment by fourroses666** [comment]
oké cool :)

**Comment by glewe** [comment]
Thanks for an excellent module. Love it!
I agree with using data attributes to avoid the popup. This is what I did to avoid the title tag for now. I edited jquery.bxslider.js (version 4.1.2) and changed line 699 from 
```javascript
var title = $(this).find('img:first').attr('title');
```
to
```javascript
var title = $(this).find('img:first').attr('data-title');
```
I then changed my img attributes accordingly. It works well and I  hope this does not mess up anything else.
I am happy to hear you are planning a new release using data attributes.

Thanks again and best regards
George
