### ISSUE TITLE
Prev button not working on first slide

### ISSUE THREAD

**Issue by synergies** [stevenwanderski/bxslider-4#758]
Here is our current code:
```javascript
$('.slides').bxSlider({
	auto: true,
	nextText: '',
	pager: false,
	prevText: '',
});
```

I can click on Next button and it goes to the next slide, from there I can click on Prev button and it goes to the first slide.  However, on load, if I click on the Prev button it breaks both buttons from working.  Any help would be greatly appreciated!

**Comment by iBook140** [comment]
Hello,

I have the exact same problem with this version. The problem started with 4.2.2 I think, I'm not sure, but I think that this is because transition-duration is set to 0. On Safari (iPad and OS X Yosemite) the image doesn't display and there is no transition when sliding back, Google Chrome shows a half image. 

This only occurs when sliding back on the first slide (to the previous slide). 

A fix would be great. 

TIA René

**Comment by synergies** [comment]
Bump.

**Comment by Tidal-Wave** [comment]
I am sprinting on the next update so I will take a look at this.

**Comment by synergies** [comment]
Thanks Eric!

**Comment by ndbroadbent** [comment]
Hi,

I'm also seeing a problem with transitions, when clicking the previous button on the first slide (to the previous slide, with infinite loop). When you click the previous button, the final slide is shown instantly. But if you then click the next button (from the final slide to the first slide), it animates properly.

Here's a demo screencap:

![bxslider-bug2](https://cloud.githubusercontent.com/assets/139536/6770363/5513b0f6-d0e8-11e4-9218-8cb1c960c1f2.gif)

**Comment by Tidal-Wave** [comment]
Issue will be addressed in 4.2.4, The problem came from an experimental attempt to address an edge case in setPositionProperty that we will be removing. Please do not implement @ndbroadbent's PR. I hope to push very soon. @iBook140 the transition-duration change is needed for the clone technique, that is purposeful. 

If you need immediate fix for this, please use the following in `setPostitionProperty`: 
```
if (type === 'slide') {
  // set the property value
  el.css(slider.animProp, propValue);
  // bind a callback method - executes when CSS transition completes
  el.bind('transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd', function() {
    // unbind the callback
    el.unbind('transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd');
    updateAfterSlideTransition();
  });
} 
```

**Comment by romapad** [comment]
Thanks for patch, did I put it correctly:
http://gps-production.ru/ostin-leto-2014-mart-2014/

**Comment by ndbroadbent** [comment]
ARGH!! You got me. Well played, spammer.

**Comment by ndbroadbent** [comment]
Oh, you were testing the slider! Haha, sorry. That really looked like spam for a minute.

**Comment by romapad** [comment]
Yes, this is slider test, but on the live site, sorry

**Comment by romapad** [comment]
As I could see there is still problem with transition

**Comment by Tidal-Wave** [comment]
Can you try pulling the development branch and see if that fixes the issue. The development branch has the current 4.2.4 WIP. It is stable, I just have a few small items and documentation things to finish before I push to master.
