### ISSUE TITLE
InfiniteLoop stops working when mode is 'fade'

### ISSUE THREAD

**Issue by djfileru** [stevenwanderski/bxslider-4#766]

**Comment by Tidal-Wave** [comment]
In testing both 4.2.3 and the 4.2.4 update that is coming I have not experienced this issue. Since no additional information was provided I am closing. Please provide a simplified example of the issue you are reporting when submitting an issue, and also please do not submit an issue with no description what so ever. If you would like assistance please respect our work and at least satisfy the guidelines.  Once you can provide this I will be happy to reopen.
