### ISSUE TITLE
Removing "alt" from bx-clone (duplicated images when infinite loop is true) 

### ISSUE THREAD

**Issue by kiyokyo** [stevenwanderski/bxslider-4#773]
When I "true" infinite loop, image will be duplicated before first image and after last image (li tag with class of "bx-clone").
I don't want to repeat alt text for duplicated image.
Will someone teach me how to remove alt text only for duplicated images (not for original images)?

Because I heard now Google can read js file.
So I don't want google to see same text.

Any advice will help.
Thank you in advance.

**Comment by Tidal-Wave** [comment]
Im not sure what Google scanning JS has to do with this question. The alt attribute content would never be in the JS file. 

Either way, if it's something that you really need for some reason (Which I also don't get because the clone is the same image as the original so not having the alt would actually be not be semantic) you can use some basic Javascript to select the clone and clear the alt attribute. 

`$('.bx-clone').removeAttr('alt');` should do it (untested off the top of my head.)
