### ISSUE TITLE
Enable on.click function for bxslider

### ISSUE THREAD

**Issue by ledjape** [stevenwanderski/bxslider-4#779]
I need help with creating a js function that will enable the slides to move to the next one - when the user right-mouse-clicks anywhere within the current slide/picture.

I've added the same class attribute to all images in the slideshow. I just need the js to get it working. 

Can I get some help on this? Thanks

**Comment by Tidal-Wave** [comment]
Take a look at this: http://jsfiddle.net/Kn9s7/5/

Basically the right click is known as the `contextmenu` event. Using this you should be able to then call `goToNextSlide` function.

Be aware that there will be some pitfalls to doing this because there is more than one way to fire the `contextmenu`, you can read about it here: http://stackoverflow.com/questions/1206203/how-to-distinguish-between-left-and-right-mouse-click-with-jquery
