### ISSUE TITLE
Loader issue

### ISSUE THREAD

**Issue by joeynimu** [stevenwanderski/bxslider-4#823]
Hi,
This is not a major issue per say but i have experienced it a couple of times so i thought to shoot it over here. I have experienced when i have a loading animation that fadesOut and the content fadeIn, the bxslider doesn't load it's contents. I don't know why is that?

For instance, i have a simple mark up as shown below
```html
<div class="loader__holder">
		<div class="loader__inner">
			 <img src="/images/loader.gif">
		</div>		
	</div>
<div class="wrapper">
<div class="slider">
<ul class="bxslider>
<li><img src="images/slider_one.jpg" /></li>
<li><img src="images/slider_two.jpg" /></li>
</ul>
</div>
<!--other contents-->
</div>
```
Then i have my simple js as below;
```javascript
jQuery(document).ready(function($){
$(window).load(function (){
      $('.loader__holder').fadeOut('fast');
      $('.wrapper').fadeIn(1000);
	});
var slider = $('.bxslider');
$(slider).bxSlider({auto: true, speed: 1000, pause: 7000});

});
```
After the loader div fadesOut and the wrapper fadesIn, all the content is okay but the slider just shows the nav circles only without the content. any ideas why this is so? 

Thanks.

**Comment by Tidal-Wave** [comment]
What version of the plugin are you using? The one available for download on the site has issues with loading. I don't currently have access to control the site, so if you are using this version please update with the latest from the repository. 

Past that, it sounds like you have an issue with the slider not being aware of it's contents size and so it initializes with a height of 0. This probably happens because the `(document).ready` fires the slider init first before `(window).load` function has a chance to fire. There are a few ways to deal with this. `preloadImages: 'all'` could help, but more then likely you will need to execute `reloadSlider()` after the wrapper is faded in. 

HTH

**Comment by joeynimu** [comment]
Thank you very much @Tidal-Wave this did the trick, cheers!
