### ISSUE TITLE
[bug] Slider stucks in slider.working when goToSlide(qty+1) without infiniteLoop

### ISSUE THREAD

**Issue by ppowalowski** [stevenwanderski/bxslider-4#835]
Slider stucks in `slider.working` when calling `goToSlide(qty+1)` when current index is PagerQty.
I'll fix and PR this.

**Comment by ppowalowski** [comment]
See PR #836

**Comment by Tidal-Wave** [comment]
fixed in 4.2.5

**Comment by withgallantry** [comment]
This has introduced a bug where clicking the next arrow quickly and repeatedly causes the index to update due to the index being set before the check to see if it's working. Visual effect is that the carousel slides one page over and doesn't update when clicking the next or prev buttons because the index is out of sync with that being displayed.
