### ISSUE TITLE
Change slide during animation bug

### ISSUE THREAD

**Issue by DzmVasileusky** [stevenwanderski/bxslider-4#920]
The issue occurs in the latest version 4.2.5. The bug don't appear in 4.1.2 which is in examples on the site.

Clicking on controls or pager items during slide change animation breaks slides' order. For example, if I move it to slide 4 and click during animation on the pager item for slide 1, the current visible slide remains - 4, but the position in bxslider object changes to 1. Then if I click next control, it will move to slide 2 not to slide 5 (for an user it appears like strange teleport from 4 to 2).
The controls should be blocked during animation like it was in earlier versions. Or current visible slide should corresponds to changed index.

And of course the fiddle 
http://jsfiddle.net/fv10sqh0/2/

**Comment by DzmVasileusky** [comment]
Find out, where is the root of the bug.

```
// store the old index
slider.oldIndex = slider.active.index;
//set new index
slider.active.index = setSlideIndex(slideIndex);

// if plugin is currently in motion, ignore request
if (slider.working || slider.active.index === slider.oldIndex) { return; }
```

On each goToSlide function during animation a new index is set, but slide won't change. I think, that index changing should be connected with slide change or we will have that awful bug.

**Comment by jamadam** [comment]
I tested this patch and works fine for me. Thank you.

And let me add that the bug sometimes causes the slider to be touch unresponsible and even virtically unscrollable. If the silder is too large in the screen, the whole page is virtually out of control.

iOS9.0.2
AppleWebKit/601.1.46

**Comment by DzmVasileusky** [comment]
Not at all, jamadam.
I think that fix should be merged soon.

**Comment by minauen** [comment]
the fix you have to apply is restoring the slider.active.index to the slider.oldIndex
slider.active.index = slider.oldIndex; // restore old index
before you return out of the goToSlide function, when the slider is working
`// store the old index
slider.oldIndex = slider.active.index;
//set new index
slider.active.index = setSlideIndex(slideIndex);

// if plugin is currently in motion, ignore request
if (slider.working || slider.active.index === slider.oldIndex) { 
slider.active.index = slider.oldIndex;
return; 
}`

otherwise the next button will be blocked by the rule slider.active.index === slider.oldIndex

**Comment by CristinaWang** [comment]
Any progress on this bug? I am facing the same issue here? It still happens on the latest version.

**Comment by sekmenhuseyin** [comment]
this issue has fixed. thanks for your comment
